version: '3'
services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb 
    environment:
      MONGO_URI: "mongodb://mongodb:27017/TaskManager"  

volumes:
  mongodb_data: 
