version: '3'
services:
  # MongoDB için servis tanımı
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Python uygulaması için servis tanımı
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb  # Python uygulaması, MongoDB'nin başlamasını bekler
    environment:
      MONGO_URI: "mongodb://mongodb:27017/TaskManager"  # MongoDB bağlantı adresi

volumes:
  mongodb_data:  # MongoDB verileri için bir volume
