---
name: python app
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Docker
    runs-on: custom-runner
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sametustaoglu/python-app:${{ github.sha }}
  
    
  scan:
    name: Scan Image
    runs-on: custom-runner
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate tarball from image
      run: |
        docker pull docker.io/sametustaoglu/python-app:${{ github.sha }}
        docker save -o vuln-image.tar docker.io/sametustaoglu/python-app:${{ github.sha }}
        
    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'

    # - name: Install Trivy
    #   run: |
    #     wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
    #     tar zxvf trivy_0.18.3_Linux-64bit.tar.gz
    #     sudo mv trivy /usr/local/bin/
    #   shell: bash

    # - name: Security Scan with Trivy
    #   run: |
    #     trivy --exit-code 0 --severity HIGH,CRITICAL sametustaoglu/python-app:${{ github.sha }} > trivy_report.txt
    #   working-directory: .

    - name: Upload Report to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        

    - name: Upload Report
      run: |
        aws s3 cp trivy_report.txt s3://samet-trivy/trivy_report_${{ github.sha }}.txt
      working-directory: .
  


      