---
name: python app
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Docker
    runs-on: custom-runner
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sametustaoglu/python-app:${{ github.sha }}
  
    
  scan:
    name: Scan Image
    runs-on: custom-runner
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate tarball from image
      run: |
        docker pull docker.io/sametustaoglu/python-app:${{ github.sha }}
        docker save -o vuln-image.tar docker.io/sametustaoglu/python-app:${{ github.sha }}
        
    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'


 
  


      